### PR TITLE
Global update

### PR DESCRIPTION
**Pull request by steph78630**
- Add Windows 10 compatibility
- Compact columns name (suppress horizontal scroll)
- Change columns order ("process name" in first)
- Change Wscript.echo method (more vbs user-friendly display)

### CODE REVIEW

**Comment by MyTheValentinus** [comment]
Hello
Regression, refused. Please create another PR with only VBS update and infos.json.

Thanks for your contribution ;)

**Comment by githug-gondios** [comment]
Hi.

The runningProcess.vbs from commit e8bed9d.... not work in my client. I have done some changes in it. What is the procedure to upload this change for your revision?

Kind regards.

**Comment by steph78630** [comment]
Hi @githug-gondios ,

Bad version diffused, sorry for this inconvenience.

You can fork this project on GitHub or send me your modified version : steph78630@gmail.com

Kind regards, Stéphane

**Comment by githug-gondios** [comment]
Hi.

Decode de attach: 'unzip runningprocess.vbs.b64.zip ; openssl enc -a -d -in runningprocess.vbs.b64 -out runningprocess.vbs

[runningprocess.vbs.b64.zip](https://github.com/PluginsOCSInventory-NG/runningProcess/files/1205401/runningprocess.vbs.b64.zip)


Kind regards.

**Comment by MyTheValentinus** [comment]
Hello @githug-gondios why you encode attachment ?

Thanks

**Comment by steph78630** [comment]
Thanks @githug-gondios !

A new version soon...

Kind regards, Stéphane

**Comment by githug-gondios** [comment]
Sorry for the encode. I wanted to upload the file in encode format but github not support it. I would have to compress the vbs script in a zip but I done the .vbs.b64

**Pull request closed without merging**
